
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApp
{

using System;
    using System.Collections.Generic;
    
public partial class DeviceGIO
{

    public int ioId { get; set; }

    public string ioName { get; set; }

    public Nullable<int> ioType { get; set; }

    public string ioValue { get; set; }

    public int ioDeviceId { get; set; }



    public virtual Devices Devices { get; set; }

}

}
