
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApp
{

using System;
    using System.Collections.Generic;
    
public partial class stuff_Has_Device
{

    public string stuff { get; set; }

    public int device { get; set; }

}

}
