
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApp
{

using System;
    using System.Collections.Generic;
    
public partial class Stuff
{

    public string stfId { get; set; }

    public string stfFullName { get; set; }

    public string stfLocation { get; set; }

    public string stfLastActivity { get; set; }

    public string stfPblSrvc { get; set; }

    public Nullable<int> stfDevice { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

}

}
